### ISSUE TITLE
Scrolling is wonky on login page and takes up a lot of cpu for no reason.

### ISSUE THREAD

**Issue by michaelplzno** [mesosoi/silverwaregames-io-issue-tracker#185]
Just make it scroll normally plzyes.

**Comment by mesosoi** [comment]
It scrolls just fine, and the CPU usage is probably due to another script called `tilt.js`, which is for cool animations. I've disabled the latter for mobile devices, where the hogging resources problem is most important. Should be better now. https://github.com/mesosoi/silverwaregames-io-issue-tracker/issues/243
