### ISSUE TITLE
Need SWGIO backend to work on native iOS, Android, and XBOX games.

### ISSUE THREAD

**Issue by michaelplzno** [mesosoi/silverwaregames-io-issue-tracker#361]
I'm not sure if this works already where a user can login and get the API key for something like an XBOX game or android game but we need to get users connected in all our apps.

**Comment by Miragebell** [comment]
Since it's all based on requests, it should be possible to integrate SWGIO into downloadable games. You said you want it to be possible to log in right inside the game, without prompting the player to use the browser. There's already a method for that, `get.key.manual`, takes email and password and returns the key. And then you can do anything with the key, just like in HTML5 games.

**Comment by michaelplzno** [comment]
ok I'll try to integrate puzzlenox next and see if it works.
